show tables;
select * from employees;
select first_name "FIRST NAME" , last_name "LAST NAME" from employees;
select distinct department_id from employees;
select * from employees order by first_name desc;
select first_name, last_name, salary, salary*0.15 "PF" from employees;
select employee_id, first_name, last_name, salary from employees order by salary;
select sum(salary) from employees;
select max(salary) "Max Salary", min(salary) "Min Salary" from employees;
select avg(salary) "Avg Salary", count(*) "Num Emp" from employees;
select count(distinct(job_id)) from employees;
select upper(first_name) from employees;
select substring(first_name,1,3) from employees;
select concat(first_name, ' ', last_name) from employees;
select length(concat(first_name, last_name)) from employees;
select * from employees where first_name regexp '[0-9]';
select * from employees limit 10;
select round(salary/12, 2) from employees;